#!/bin/bash
# Install Apache Web Server and PHP
yum install -y httpd mysql php
# Download Lab files
wget https://aws-tc-largeobjects.s3.us-west-2.amazonaws.com/CUR-TF-100-ACCLFO-2/2-lab2-vpc/s3/lab-app.zip
unzip lab-app.zip -d /var/www/html/
# Turn on web server
chkconfig httpd on
service httpd start
systemctl enable httpd
mkdir /var/www/html/maruti/
echo "<h1>This is maruti App</h1>" > /var/www/html/maruti/index.html
systemctl start httpd
